### ISSUE TITLE
Buglet in SelectScriptFromExistingOnes()

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/UnitTestToolbox#1]
This has hard coded isetbio's listing function on line 2, but should draw this info from the preferences.  Causes this script to fail when run for repositories other than isetbio.

**Comment by npcottaris** [comment]
This should be fixed now. As always git pull on  the UnitTestToolbox and test.
Let me know if there is a problem.

N.

**Comment by DavidBrainard** [comment]
Thanks!
