### ISSUE TITLE
Problem with Geoff's macbook's hostname

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/UnitTestToolbox#12]
We think we just put in a fix that will handle the case where Java can't get the hostname.  This might still crash in that case on Windows, but if it fixes the current problem we will be happy.

Geoff, can you test on your machine?  If it works, close the issue.

**Comment by benjamin-heasly** [comment]
For reference, here is our PR with our attempt to fix:
  https://github.com/isetbio/UnitTestToolbox/pull/11

**Comment by DavidBrainard** [comment]
This fixed with our recent little try-catch tweak.
