### ISSUE TITLE
Message that figs available on fail

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/UnitTestToolbox#2]
When a full validation fails, there is a message that says to look at some figures, but I am pretty sure these figures only get generated when some flag is set, and the message is confusing when that flag isn't set.

Or if they are being generated, I need more hints about where they are stored.

**Comment by npcottaris** [comment]
It is not that validation figs are not generated. They are but they are closed by ieinit at the beginning of the next script. It you want to see them try validateFullOne with the failed script. The other alternative is to change ieinit so it does not close all figures, but only those with a figure number that is less than a specific number (say 9999) and then have UnitTest  toolbox generate validation figures in the range 10000 and upwards.
