### ISSUE TITLE
Configuration convention

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/UnitTestToolbox#5]
When we autoconfigure a new project for the UnitTestToolbox, we would like the names of the validation scripts to begin with some specified prefix (e.g., ieValidateFastAll, ieValidateFullAll, ....).  That will help us avoid namespace collisions.

**Comment by npcottaris** [comment]
This is now implemented. The script `ConfigureUnitTestValiationNewProject` asks the user 6 questions and generates the entire validation mechanism.
